<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="P3DFile\P3DParser.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ProtoType2.Tools.RadpToWav">
      <HintPath>..\..\ProtoType2.Tools\ProtoType2.Tools.RadpToWav\bin\Debug\net8.0\ProtoType2.Tools.RadpToWav.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>